//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.21 at 10:31:45 AM BDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.abbyy.com/FlexiCapture/Schemas/Export/FormData.xsd", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package io.naztech.nuxeoclient.model.invoice.MMA;
